#!/bin/bash

if [ "$HOST" != "ahso" ]; then
	echo "You're not on the ahso." >&2
	echo "Run" >&2
	echo "  ant create_release_release" >&2
	echo "instead." >&2
	exit 1
fi

prefix=$1
cp dist/upload/* /home/stefan/www/joerg.endrullis.de/jlatexeditor/update/
cp dist/releases/$prefix.* /home/stefan/www/joerg.endrullis.de/jlatexeditor/releases/
