#!/bin/bash
#
# Please do not edit this file directly since it may change over time and your edits could result in svn conflicts.
# Instead try to set all your system specific variables in your ~/.jlatexeditor/settings.conf, e.g. JAVA_HOME
# and JAVA_OPTS.

USER_PWD=`pwd`

# if there is only one argument which is not an option then it must be a file which we could try to open directly
if [ $# == 1 ]; then
	if echo "$1" | grep -q "^[^-]"; then
		file="$1"

		# local path? => make absolute
		if echo "$file" | grep -q "^[^\/]"; then
			file="$USER_PWD/$file"
		fi

		echo "open: $file" | nc -w 1 localhost 13231 2>/dev/null && exit 0
	fi
fi

JLE_SCRIPT=`readlink -f $0`
if [ "$JLE_SCRIPT" = "" ]; then
	# use direct path for Mac users
	JLE_SCRIPT=$0
fi

cd `dirname $JLE_SCRIPT`

LIB=""
for file in `ls lib/`
do
   LIB="$LIB:lib/$file"
done

# load a settings.conf if available
if [ -f ~/.jlatexeditor/settings.conf ]; then
  source ~/.jlatexeditor/settings.conf
fi

git pull origin master
ant clearDependentClasses
ant compile

MAC=""
if [ `uname` = "Darwin" ]
then
  MAC="-Xdock:name=JLatexEditor -Xdock:icon=dev/tex-cookie.png"
fi

JAVA=java

if [ "$JAVA_HOME" != "" ]; then
	JAVA="$JAVA_HOME/bin/java"
fi

$JAVA -Xmx200M $MAC $JAVA_OPTS "-Djlatexeditor.working_dir=$USER_PWD" -cp build/classes/$LIB jlatexeditor.JLatexEditorJFrame "$@"
