#!/bin/bash
cp pack.temp.dmg temp.dmg

wget http://endrullis.de/JLatexEditor/releases/JLatexEditor-latest.tar.gz
tar xfz JLatexEditor-latest.tar.gz
rm JLatexEditor/.wstart.bat
rm JLatexEditor/jlatexeditor.bat
mv JLatexEditor/* content/JLatexEditor.app/Contents/MacOS/ 
rmdir JLatexEditor
rm JLatexEditor-latest.tar.gz

cp ../dev/images/cookie-icon/tex-cookie_512.png content/JLatexEditor.app/Contents/MacOS/tex-cookie.png

export device=$(hdiutil attach -readwrite -noverify -noautoopen "temp.dmg" | egrep '^/dev/' | sed 1q | awk '{print $1}')

read

chmod -Rf go-w /Volumes/JLatexEditor/
sync
sync
hdiutil detach ${device}
rm JLatexEditor.dmg
hdiutil convert "temp.dmg" -format UDZO -imagekey zlib-level=9 -o "JLatexEditor.dmg"

rm -rf content/JLatexEditor.app/Contents/MacOS/*
rm -f temp.dmg
