#!/bin/bash

version=$1
prefix=JLatexEditor-$1

# tag this release
svn copy . https://endrullis.de/svn/JLatexEditor/tags/$version -m "released version $version"

cd dist/

# pack
zip -r $prefix.zip JLatexEditor
tar -czf $prefix.tar.gz JLatexEditor

mv $prefix.* releases/

# create symbolic links (last.*)
cd releases
for ext in zip tar.gz; do
	[ -e JLatexEditor-latest.$ext ] && rm JLatexEditor-latest.$ext
	ln -s $prefix.$ext JLatexEditor-latest.$ext
done

cd ../..
